### PR TITLE
Use selected piece set for auto pieces

### PR DESCRIPTION
**Pull request by romnzs**
For ornicar/lila#8302

Currently auto pieces are displayed as images in SVG shape layer and they always appear in the default (cburnett) piece set instead of the piece set selected by a user.

This could be resolved by moving auto pieces from SVG to a separate HTML layer. This allows to use the same HTML elements, classes and styles as for normal pieces. As a result auto pieces will also appear in the selected piece set.

This resolves all the situations where auto pieces are appearing, not just the situation described in the issue (promoting suggestion in analysis board). Other situations where this is relevant are, for instance, premove with a promotion in a game and drop suggestion in Crazyhouse analysis board. Probably there is more.

Tested with both 2D and 3D boards in Firefox, Chrome and Safari.

P.S. Small CSS adjustments will be needed in _lila_  in case if this PR is merged. Here is a PR draft for it - ornicar/lila#9711.

|        | Before | After |
| ------ | ------ | ----- |
| Promoting suggestion (analysis) | promotion-suggestion-before | promotion-suggestion-after |
| Premove with a promotion | pre-promotion-before | pre-promotion-after |
| Drop suggestion (analysis, Crazyhouse) | drop-suggestion-before | drop-suggestion-after |
| 3D board example | promotion-suggestion-3d-before | promotion-suggestion-3d-after |

### CODE REVIEW

**Comment by benediktwerner** [comment]
Did you check it with 3D boards?

**Comment by romnzs** [comment]
> Did you check it with 3D boards?

Didn't think of that.
Indeed, pieces are cropped in 3D boards. I will try to fix that.
Thanks for the tip!
3d-promotion-suggestion-after

**Comment by 370417** [comment]
Awesome! It works on Firefox of course, but can confirm it also works on Chrome, avoiding all the weird webkit/blink foreignObject bugs that I ran into, eg [771852](https://bugs.chromium.org/p/chromium/issues/detail?id=771852).

**Comment by romnzs** [comment]
Trying to adjust the solution for 3D boards as well as testing more carefully in different browsers I also ran into various bugs with _foreignObject_, for example when resizing/zooming a page or switching a piece set.

So, unfortunately, the solution with _foreignObject_ doesn't seem to be reliable and eventually I decided to implement an initial idea which is to move auto pieces into a separate _html_ layer alongside _svg_ (similar to ghost piece which is also located on a separate layer). 

Will update the PR.

**Comment by romnzs** [comment]
Also I've find out that currently there is an existing issue - auto pieces are positioned incorrectly in Safari.

Should also be fixed with the new solution.

safari-auto-pies-position-bug

**Comment by kraktus** [comment]
gentle bump

**Comment by ornicar** [comment]
I appreciate the work that went into this, but in my opinion this is a lot of added code, to make a very rare use case use prettier.

**Comment by ornicar** [comment]
That actually makes a lot of sense. Thank you!

**Pull request merged**
